services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 5
      timeout: 5s
    restart: always
    networks:
      - signal

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT}:80"
    depends_on:
      - postgres
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
    restart: always
    networks:
      - signal

  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "${MINIO_PORT_1}:9000"
      - "${MINIO_PORT_2}:9001"
    command: server /data --console-address ":9001"
    volumes:
      - ./data/minio:/data
      - ./config/minio:/root/.minio
    healthcheck:
      test: ["CMD", "mc", "ls", "myminio/"]
      retries: 3
      interval: 30s
    networks:
      - signal
  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    hostname: kafka
    ports:
      - "${KAFKA1_PORT}:9092"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093  # تنظیمات برای KRaft (یک گره کنترل‌کننده)
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER  # افزودن این تنظیم برای حل مشکل
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LOG_DIRS: /var/lib/kafka/data
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
    volumes:
      - ./data/kafka:/var/lib/kafka/data
    healthcheck:
      test: ["CMD", "kafka-topics.sh --bootstrap-server kafka:9092 --list"]
      interval: 10s
      retries: 3
      timeout: 5s
    restart: always
    networks:
      - signal

  kafka-manager:
    image: hlebalbau/kafka-manager:latest
    container_name: kafka-manager
    platform: linux/amd64
    environment:
      ZK_HOSTS: ""
      KAFKA_MANAGER_ARGS: "-Djava.net.preferIPv4Stack=true"
      KAFKA_PRODUCER_MAX_REQUEST_SIZE: 52428800
      KAFKA_MESSAGE_MAX_BYTES: 52428800
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
    ports:
      - "9005:9000"
    depends_on:
      - kafka
    networks:
      - signal
    restart: always

networks:
  signal:
    driver: bridge
