services:
  postgres:
    image: postgres:latest
    container_name: signal_postgres
    environment:
      POSTGRES_USER: signal
      POSTGRES_PASSWORD: signal123
      POSTGRES_DB: signaldb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # udp-server:
  #   build:
  #     context: ./service/udp-server
  #   container_name: signal_udp_server
  #   environment:
  #     DATABASE_URL: postgres://signal:signal123@postgres:5432/signaldb
  #     UDP_PORT: "8080"
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "8080:8080"

  # api:
  #   build:
  #     context: ./service/api
  #   container_name: signal_api
  #   environment:
  #     DATABASE_URL: postgres://signal:signal123@postgres:5432/signaldb
  #     API_PORT: "8081"
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "8081:8081"

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: signal_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80" 
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin
  # :
  #   image: minio/minio:latest
  #   container_name: signal_minio
  #   environment:
  #     MINIO_ACCESS_KEY: minioaccess
  #     MINIO_SECRET_KEY: miniosecret
  #   ports:
  #     - "9000:9000"
  #   volumes:
  #     - minio_data:/data
  #   command: server /data
  #   depends_on:
  #     - postgres

volumes:
  postgres_data:
  pgadmin_data:
  minio_data:
